version: '3.8'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app
  
  be:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mongodb://root:example@db:27017/inspirationalappdb?authSource=admin&ssl=false
    depends_on:
      - db
    networks:
      - app
  
  fe:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        - API=
    depends_on:
      - be
    networks:
      - app

  nginx:
    depends_on:
      - fe
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    networks:
      - app

networks:
  app: