version: '3.8'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  be:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://root:example@db:27017/inspirationalappdb?authSource=admin&ssl=false
    depends_on:
      - db
  
  fe:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - API=http://be:3000/api/quote
    depends_on:
      - be