version: '3.8'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app
  
  be:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mongodb://root:example@db:27017/inspirationalappdb?authSource=admin&ssl=false
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - app
  
  fe:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        - API=http://localhost:8080
    depends_on:
      - be
    networks:
      - app

networks:
  app: