name: deploy-fe
on:
  workflow_run:
    workflows: [deploy-be]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Heroku login credentials
        run: |
          chmod +x ./scripts/heroku-login.sh
          sh ./scripts/heroku-login.sh
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      
      - name: Add heroku.yml to root
        run: cp ./heroku/heroku-fe.yml ./heroku.yml
      - name: Put API Url
        run: sed -i 's%__API__%'"$BE_URL"'%g' heroku.yml
        env:
          BE_URL: ${{ secrets.BE_URL }}
      - name: Git Phase
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'https://github.com/saliougaye/inspirationalquotesapp'
          git add heroku.yml
          git commit -m "add heroku.yml"
          git status
      - name: Add Heroku remote
        run: heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME_FE }}
      - name: Set Heroku Stack
        run: heroku stack:set container
      - name: Push to heroku
        run: git push -f heroku feature/deploy-ci-cd:main

    